/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author Cauã
 */
@Component
public class CursoEditar extends javax.swing.JFrame {

    /**
     * Creates new form CursoEditar
     */
    
      @Autowired
      private CursoIController cursoController; // cria objeto que liga com as outras camadas do projeto
      private Curso cursoAtual;
      private final ApplicationContext applicationContext;//injeta o application context no projeto


          @Autowired  // CONSTRUTOR
                public CursoEditar(CursoIController cursoController, ApplicationContext applicationContext){
                this.cursoController = cursoController;
                this.applicationContext = applicationContext; // inicializa
                

                initComponents(); // Inicializa os componentes da GUI
                setLocationRelativeTo(null);
                this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                setTitle("Novo Curso"); // Define o título da janela
            
   
    }
    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param cursoEncontrado
     */      
       // metodo para buscar o curso a ser editado,da tela curso listar
        public void setCurso(Curso cursoEncontrado) {
        this.cursoAtual = cursoEncontrado;
         preencherCampos(); // Preenche os campos (neste caso, com valores padrão ou vazios)
        }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        cBoxAtivo = new javax.swing.JComboBox<>();
        btnConfirma = new javax.swing.JToggleButton();
        lblNovoCodigo = new javax.swing.JLabel();
        txtNovoCodigo = new javax.swing.JTextField();
        txtNovoNome = new javax.swing.JTextField();
        lblNovoNome = new javax.swing.JLabel();
        lblTituloEditar = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        lblStatus.setForeground(new java.awt.Color(0, 0, 0));
        lblStatus.setText("Status :");

        cBoxAtivo.setForeground(new java.awt.Color(0, 0, 0));
        cBoxAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", " " }));
        cBoxAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAtivoActionPerformed(evt);
            }
        });

        btnConfirma.setForeground(new java.awt.Color(0, 0, 0));
        btnConfirma.setText("CONFIRMAR");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        lblNovoCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblNovoCodigo.setText("NOVO CODIGO :");

        txtNovoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoCodigoActionPerformed(evt);
            }
        });

        lblNovoNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNovoNome.setText("NOVO NOME :");

        lblTituloEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloEditar.setText("       EDITAR DADOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cBoxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblNovoNome)
                                    .addGap(46, 46, 46)
                                    .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblNovoCodigo)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(194, 194, 194))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoNome)
                    .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirma)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoCodigo)
                    .addComponent(txtNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherCampos() { // preenche os txts da tela curso editar com os dados curso que vai ser editado

         if (cursoAtual != null) {
            txtNovoNome.setText(cursoAtual.getNome() != null ? cursoAtual.getNome() : ""); // preenche o text com o curso a ser editado
            txtNovoCodigo.setText(cursoAtual.getCodigoCurso() != null ? cursoAtual.getCodigoCurso(): ""); // preenche o text com o curso a ser editado
            
            // *** Preenche o estado do JComboBox cmbAtivo ***
            if (cBoxAtivo!= null) { // Verifica se cmbAtivo foi inicializado em initComponents
                cBoxAtivo.setSelectedItem(cursoAtual.isAtivoNoParamenter()? "Sim" : "Não");
            }

        } else {
            // Para novos cursos (quando cursoAtual é criado vazio no construtor)
            txtNovoNome.setText("");
            txtNovoCodigo.setText("");
            if (cBoxAtivo != null) {
                cBoxAtivo.setSelectedItem("Sim"); // Padrão para novo curso
            }
        }
    }
      @SuppressWarnings("null")
    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed

    try {
        cursoAtual.setNome(txtNovoNome.getText()); //recebe os dados da view
        cursoAtual.setCodigoCurso(txtNovoCodigo.getText());
        
        String selecionado = (String) cBoxAtivo.getSelectedItem();

        boolean ativo;
        if ("Ativo".equalsIgnoreCase(selecionado)) { // Case-insensitive comparison for "Ativo"
        ativo = true;
        } else {
        ativo = false; 
        }
        cursoAtual.setAtivo(ativo);
        
        if (cursoAtual.getNome().isEmpty() || cursoAtual.getCodigoCurso().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e Código são obrigatórios!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return; // Sai do método
        }else{
            //edita o curso no banco de dados
             CursoEditar cursoEditar = applicationContext.getBean(CursoEditar.class); //obtem a istancia da classe CursoEditar ja com as instancias do spring
              cursoController.update(cursoAtual);//passa para a proxima camada para atualizar
        }
        //verificacoes de erro e mensagem de conclusao
        String successMessage; 
        if (cursoAtual.getId() == null) { 
          
            successMessage = "Curso salvo com sucesso!";
        } else { 

            successMessage = "Curso atualizado com sucesso!";
        }

        JOptionPane.showMessageDialog(this, successMessage + " ID: " + String.valueOf(cursoAtual.getId()), "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        this.dispose(); 

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar curso: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void txtNovoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovoCodigoActionPerformed

    private void cBoxAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxAtivoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirma;
    private javax.swing.JComboBox<String> cBoxAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNovoCodigo;
    private javax.swing.JLabel lblNovoNome;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloEditar;
    private javax.swing.JTextField txtNovoCodigo;
    private javax.swing.JTextField txtNovoNome;
    // End of variables declaration//GEN-END:variables
}
