/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox; // Importar JCheckBox para o atributo 'ativo'
/**
 *
 * @author Cauã
 */
public class CursoEditar extends javax.swing.JFrame {

    /**
     * Creates new form CursoEditar
     */


      private Curso cursoAtual;
       
  
    public CursoEditar(EntityManagerFactory emf) {
        
    
        this.cursoAtual = new Curso(); // Cria uma nova instância de Curso para cadastro
        initComponents(); // Inicializa os componentes da GUI
        setTitle("Novo Curso"); // Define o título da janela
        preencherCampos(); // Preenche os campos (neste caso, com valores padrão ou vazios)
    }

  
    public CursoEditar(Curso cursoEncontrado) {

        this.cursoAtual = cursoEncontrado;
        initComponents();
        setTitle("Novo Curso"); // Define o título da janela
        preencherCampos(); // Preenche os campos (neste caso, com valores padrão ou vazios)
      
    }

    public CursoEditar() {
        
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTituloEditar = new javax.swing.JLabel();
        btnConfirma = new javax.swing.JToggleButton();
        txtNovoNome = new javax.swing.JTextField();
        txtNovoCodigo = new javax.swing.JTextField();
        lblNovoNome = new javax.swing.JLabel();
        lblNovoCodigo = new javax.swing.JLabel();
        cBoxAtivo = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTituloEditar.setText("       EDITAR DADOS");

        btnConfirma.setText("CONFIRMAR");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        txtNovoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovoCodigoActionPerformed(evt);
            }
        });

        lblNovoNome.setText("NOVO NOME :");

        lblNovoCodigo.setText("NOVO CODIGO :");

        cBoxAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", " " }));
        cBoxAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxAtivoActionPerformed(evt);
            }
        });

        lblStatus.setText("Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNovoCodigo)
                                .addComponent(lblNovoNome))
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBoxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNovoNome))
                .addGap(11, 11, 11)
                .addComponent(btnConfirma)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNovoCodigo))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBoxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void preencherCampos() {
         if (cursoAtual != null) {
            txtNovoNome.setText(cursoAtual.getNome() != null ? cursoAtual.getNome() : ""); // preenche o text com o curso a ser editado
            txtNovoCodigo.setText(cursoAtual.getCodigoCurso() != null ? cursoAtual.getCodigoCurso(): ""); // preenche o text com o curso a ser editado
            
            // *** Preenche o estado do JComboBox cmbAtivo ***
            if (cBoxAtivo!= null) { // Verifica se cmbAtivo foi inicializado em initComponents
                cBoxAtivo.setSelectedItem(cursoAtual.isAtivoNoParamenter()? "Sim" : "Não");
            }

        } else {
            // Para novos cursos (quando cursoAtual é criado vazio no construtor)
            txtNovoNome.setText("");
            txtNovoCodigo.setText("");
            if (cBoxAtivo != null) {
                cBoxAtivo.setSelectedItem("Sim"); // Padrão para novo curso
            }
        }
    }
      @SuppressWarnings("null")
    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed

    try {

        
        cursoAtual.setNome(txtNovoNome.getText()); //recebe os dados da view
        cursoAtual.setCodigoCurso(txtNovoCodigo.getText());
        
        String selecionado = (String) cBoxAtivo.getSelectedItem();

        boolean ativo;
        if ("Ativo".equalsIgnoreCase(selecionado)) { // Case-insensitive comparison for "Ativo"
        ativo = true;
        } else {
        ativo = false; 
        }
        cursoAtual.setAtivo(ativo);
        
        if (cursoAtual.getNome().isEmpty() || cursoAtual.getCodigoCurso().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e Código são obrigatórios!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return; // Sai do método
        }else{
            //edita o curso no banco de dados
              CursoIDao cursoDao = new CursoDao();
              cursoDao.Update(cursoAtual);
        }
        //verificacoes de erro e mensagem de conclusao
        String successMessage; 
        if (cursoAtual.getId() == null) { 
          
            successMessage = "Curso salvo com sucesso!";
        } else { 

            successMessage = "Curso atualizado com sucesso!";
        }

        JOptionPane.showMessageDialog(this, successMessage + " ID: " + String.valueOf(cursoAtual.getId()), "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        this.dispose(); 

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar curso: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void txtNovoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovoCodigoActionPerformed

    private void cBoxAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBoxAtivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirma;
    private javax.swing.JComboBox<String> cBoxAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNovoCodigo;
    private javax.swing.JLabel lblNovoNome;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTituloEditar;
    private javax.swing.JTextField txtNovoCodigo;
    private javax.swing.JTextField txtNovoNome;
    // End of variables declaration//GEN-END:variables
}
