/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Cauã
 */

@Component
public class CursoCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form CursoCadastrar
     */
       @Autowired
       private CursoIController cursoController ; // cria objeto que liga com as outras camadas do projeto
       
       
    // Construtor padrão da classe CursoCadastrar.
    // É chamado quando uma nova instância de CursoCadastrar é criada (ex: new CursoCadastrar()).
    @Autowired
    public CursoCadastrar() {
        // Este método é responsável por inicializar todos os componentes da interface gráfica (botões, campos de texto, etc.)
        // e organizá-los no layout da janela.
        initComponents();
        // Define a posição inicial da janela na tela para ser centralizada.
        // O valor 'null' indica que a janela deve ser centralizada em relação à tela.
        setLocationRelativeTo(null);
        // JFrame.DISPOSE_ON_CLOSE significa que, ao fechar esta janela, apenas ela será descartada
        // e seus recursos liberados, mas a aplicação principal (outras janelas) permanecerá em execução.
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVermelho = new javax.swing.JPanel();
        pnlBranco = new javax.swing.JPanel();
        txtCodigoCadastro = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtnomeCadastro = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVermelho.setBackground(new java.awt.Color(255, 0, 0));
        pnlVermelho.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlVermelhoLayout = new javax.swing.GroupLayout(pnlVermelho);
        pnlVermelho.setLayout(pnlVermelhoLayout);
        pnlVermelhoLayout.setHorizontalGroup(
            pnlVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pnlVermelhoLayout.setVerticalGroup(
            pnlVermelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        getContentPane().add(pnlVermelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, -1));

        pnlBranco.setBackground(new java.awt.Color(255, 255, 255));

        txtCodigoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoCadastroActionPerformed(evt);
            }
        });

        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("CODIGO :");

        txtnomeCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeCadastroActionPerformed(evt);
            }
        });

        lblNome.setBackground(new java.awt.Color(102, 102, 102));
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("NOME :");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("          CADASTRAR");

        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBrancoLayout = new javax.swing.GroupLayout(pnlBranco);
        pnlBranco.setLayout(pnlBrancoLayout);
        pnlBrancoLayout.setHorizontalGroup(
            pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(pnlBrancoLayout.createSequentialGroup()
                .addGroup(pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBrancoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBrancoLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBrancoLayout.createSequentialGroup()
                                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBrancoLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        pnlBrancoLayout.setVerticalGroup(
            pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBrancoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtnomeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addGap(2, 2, 2)
                .addGroup(pnlBrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 540, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeCadastroActionPerformed

    private void txtCodigoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCadastroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Curso novoCurso = new Curso();
        novoCurso.setNome(txtnomeCadastro.getText()); // recebe os dados do txt
        novoCurso.setCodigoCurso(txtCodigoCadastro.getText());

        if (novoCurso.getNome().isEmpty() || novoCurso.getCodigoCurso().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e Código são obrigatórios!", "Erro de Validação", JOptionPane.WARNING_MESSAGE); // verifica se tem a
            return;
        }

        novoCurso.setAtivo(true);

        // Adicionado bloco try-catch para depuração e tratamento de erros
        try {
            // salva no banco de dados

            cursoController.save(novoCurso); //passa para a proxima camada
            JOptionPane.showMessageDialog(this, "Curso salvo com sucesso! ID: " + novoCurso.getId(), "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            txtnomeCadastro.setText("");
            txtCodigoCadastro.setText(""); // teste de validação
        } catch (Exception e) {
            // Imprime o stack trace no console para detalhes do erro
            e.printStackTrace();
            // Exibe uma mensagem de erro amigável ao usuário
            JOptionPane.showMessageDialog(this, "Erro ao salvar curso: " + e.getMessage(), "Erro no Banco de Dados", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlBranco;
    private javax.swing.JPanel pnlVermelho;
    private javax.swing.JTextField txtCodigoCadastro;
    private javax.swing.JTextField txtnomeCadastro;
    // End of variables declaration//GEN-END:variables
}
