/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.model.table.CursoTableModel;
import br.com.ifba.curso.entity.Curso;
import java.util.List;
import java.awt.event.WindowAdapter; // Importar para WindowListener
import java.awt.event.WindowEvent;   // Importar para WindowListener
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import org.springframework.stereotype.Component;


/**
 *
 * @author Cauã
 */
@Component
public class CursoListar extends javax.swing.JFrame {

    /**
     * Creates new form CursoListar
     */

   private CursoTableModel cursoTableModel;
   @Autowired
   private CursoIController cursoController;// cria objeto que liga com as outras camadas do projeto
   private final ApplicationContext applicationContext; //injeta o application context no projeto
    
   @Autowired
    public CursoListar(CursoController cursoController, ApplicationContext applicationContext ) {
        
        this.cursoController = cursoController;   
        this.applicationContext = applicationContext;
        this.cursoTableModel = new CursoTableModel();
        initComponents();
        // Configura o TableModel para a JTable (substituindo o DefaultTableModel)
        tableCurso.setModel(cursoTableModel); // tableCurso é o nome da sua JTable
        carregarCursos();


    }
    
    // metodo para carregar os cursos no jtable
    private void carregarCursos(){
        
         try{
             List<Curso> cursos = cursoController.findAll();
             cursoTableModel.setCursos(cursos);             
         }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Erro ao carregar cursos"+ e.getMessage(),"Erro", JOptionPane.WARNING_MESSAGE);
                 e.printStackTrace();
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlAzulClaro = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnDeletar = new javax.swing.JToggleButton();
        lblLista = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JToggleButton();
        pnlAZUL = new javax.swing.JPanel();
        btnListar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCurso = new javax.swing.JTable();
        lblPesquisa = new javax.swing.JLabel();
        lblAtencao = new javax.swing.JLabel();
        lblRecado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAzulClaro.setBackground(new java.awt.Color(255, 255, 255));
        pnlAzulClaro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\prg03presistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\adicioonar.png")); // NOI18N
        btnCadastrar.setText("NOVO");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 110, 50));

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\prg03presistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\EDITAR.png")); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setMaximumSize(new java.awt.Dimension(100, 135));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 110, 50));

        btnDeletar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauã\\OneDrive\\Documentos\\NetBeansProjects\\prg03presistencia\\src\\main\\java\\br\\com\\ifba\\curso\\images\\excluir.png")); // NOI18N
        btnDeletar.setText("EXCLUIR");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 110, 50));

        lblLista.setForeground(new java.awt.Color(255, 255, 255));
        lblLista.setText("LISTA");
        pnlAzulClaro.add(lblLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 150, 30));

        txtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 190, -1));

        btnPesquisar.setText("...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 30, 20));

        pnlAZUL.setBackground(new java.awt.Color(255, 0, 0));
        pnlAzulClaro.add(pnlAZUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 80));

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnlAzulClaro.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 50));

        tableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCurso);

        pnlAzulClaro.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 640, 300));

        lblPesquisa.setForeground(new java.awt.Color(0, 0, 0));
        lblPesquisa.setText("Pesquisar :");
        pnlAzulClaro.add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, -1, 20));

        lblAtencao.setBackground(new java.awt.Color(255, 255, 255));
        lblAtencao.setForeground(new java.awt.Color(204, 0, 0));
        lblAtencao.setText("Atenção");
        pnlAzulClaro.add(lblAtencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, -1, -1));

        lblRecado.setForeground(new java.awt.Color(255, 0, 0));
        lblRecado.setText("A pesquisa é feita pelo nome do curso");
        pnlAzulClaro.add(lblRecado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, -1, -1));

        getContentPane().add(pnlAzulClaro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
    int selectedRow = tableCurso.getSelectedRow(); // Obtém o índice da linha selecionada

        if (selectedRow == -1) { // Verifica se alguma linha foi selecionada
            JOptionPane.showMessageDialog(this, "Por favor, selecione um curso na tabela para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtém o objeto Curso completo da linha selecionada através do TableModel
        Curso cursoParaEditar = cursoTableModel.getCurso(selectedRow);

        if (cursoParaEditar != null) {

            CursoEditar cursoEdit = applicationContext.getBean(CursoEditar.class); // obtem a instancia a classe CursoEditar
            cursoEdit.setCurso(cursoParaEditar);
            cursoEdit.setVisible(true);

            // Adiciona um listener para a tela secundária. Quando ela fechar, a lista é recarregada.
            cursoEdit.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    btnListarActionPerformed(null); // Recarrega a lista na JTable
                }
            });

        } else {
            // Isso só deve acontecer se houver um erro lógico no TableModel
            JOptionPane.showMessageDialog(this, "Não foi possível carregar os detalhes do curso selecionado.", "Erro Interno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
         
        CursoCadastrar cursoCadastrar = applicationContext.getBean(CursoCadastrar.class); //obtem a instacia da tela CursoCadastrar

        cursoCadastrar.setVisible(true);
        carregarCursos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

 
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
    
     int selectedRow = tableCurso.getSelectedRow(); //seleciona da tabela
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um curso para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Curso cursoParaExcluir = cursoTableModel.getCurso(selectedRow);
        if (cursoParaExcluir == null) {
            JOptionPane.showMessageDialog(this, "Não foi possível obter o curso para exclusão.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                      "Tem certeza que deseja excluir o curso: " + cursoParaExcluir.getNome() + " (ID: " + cursoParaExcluir.getId() + ")?", 
                      "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
   
                // Primeiro, encontre a entidade gerenciada antes de remover
                      
                      cursoController.findById(cursoParaExcluir.getId()); // usa o findbyid pra prcurar o curso no banco
                if ( cursoParaExcluir != null) { // se existir
                    
                    cursoController.delete(cursoParaExcluir); //apaga do banco
                    JOptionPane.showMessageDialog(this, "Curso excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    btnListarActionPerformed(null); // Recarrega a lista
                } else {
                    JOptionPane.showMessageDialog(this, "Curso não encontrado para exclusão.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
           
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
   
        String termoPesquisa = txtPesquisar.getText();

    try {
      
        
        List<Curso> cursosFiltrados = cursoController.findByNome(termoPesquisa); //usa um metodo criado no cursoDao para pesquisar pelo nome do curso

        cursoTableModel.setCursos(cursosFiltrados != null ? cursosFiltrados : new ArrayList<>()); 

        // verifica se a lista de resultados é nula ou vazia
        if (cursosFiltrados == null || cursosFiltrados.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Nenhum curso encontrado para o termo: \"" + termoPesquisa + "\"", "Pesquisa Vazia", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erro ao pesquisar cursos: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace(); // imprime a pilha de erros no console
    }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
    
              try{
             List<Curso> cursos = cursoController.findAll();
             cursoTableModel.setCursos(cursos);
             if(cursos.isEmpty()){
                          JOptionPane.showMessageDialog(this, "Nenhum curso encontrado","Erro", JOptionPane.WARNING_MESSAGE);
             }
             }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Erro ao carregar cursos"+ e.getMessage(),"Erro", JOptionPane.WARNING_MESSAGE);
                 e.printStackTrace();
       
             }
                                         
       
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JToggleButton btnDeletar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnListar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtencao;
    private javax.swing.JLabel lblLista;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblRecado;
    private javax.swing.JPanel pnlAZUL;
    private javax.swing.JPanel pnlAzulClaro;
    private javax.swing.JTable tableCurso;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
